version: '3.8'
services:
  postgresql:
    image: 'bitnami/postgresql:15.2.0'
    networks:
      - public
    ports:
      - '5632:5432'
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=dsa
      - POSTGRESQL_PASSWORD=password
  postgresql-init:
    image: 'bitnami/postgresql:15.2.0'
    networks:
      - public
    environment:
      - PGUSER=dsa
      - PGPASSWORD=password
    depends_on:
      - postgresql
    restart: 'no'
    command:
      - /bin/sh
      - -c
      - |
        while ! pg_isready -d postgres -h postgresql -p 5432 -U "dsa"; do sleep 1; done;
        echo "SELECT 'CREATE DATABASE data_structure' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'data_structure')\gexec" | psql -h postgresql -p 5432 --user "dsa" -d postgres;
  nats:
    image: 'nats:2.9.15-alpine'
    networks:
      - public
    ports:
      - '4222:4222'
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
    restart: unless-stopped

networks:
  public:
    driver: bridge
    internal: false
